title: ProductStatusEnum
x-stoplight:
  id: fd02d09fa64e8
type: integer
enum:
  - 0
  - 1
  - 2
description: |
  Descriptor for Product Status <br> Where:
  * 0 - Item in early phase. Should not be accepted neither by RVM or Manual Collection 
  * 1 - Item should be accepted by RVM and Manual Collection.
  * 2 - RVM and Manual Collection should reject those items
