title: ProductPost
x-stoplight:
  id: sza93xu1duwl4
type: object
required:
  - market
  - biodegradable
  - inDepositSystem
allOf:
- $ref: 'ProductBase.yaml'
- type: object
  properties:
    sleeveLabel:
      description: Does packaging contains sleeve label
      type: boolean
      x-stoplight:
        id: ezwage8aqsa4e
    comment:
      type: string
    status:
      $ref: "enum/StatusEnum.yaml"
    biodegradable:
      type: boolean
      description: Is product biodegradable
    inDepositSystem:
      type: boolean
      description: Is product in deposit system
    test:
      type: object
      properties:
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
    market:
      type: object
      properties:
        entryDate:
          type: string
          format: date-time
          x-stoplight:
            id: jovvcg3atuc82
        exitDate:
          type: string
          format: date-time
          x-stoplight:
            id: fjy6meqa13h6z
      x-stoplight:
        id: ap1aw4pc0eibf
