title: ProductPost
x-stoplight:
  id: sza93xu1duwl4
type: object
required:
  - market
  - biodegradable
  - inDepositSystem
allOf:
- $ref: 'ProductBase.yaml'
- type: object
  properties:
    biodegradable:
      type: boolean
      description: Is product biodegradable
    inDepositSystem:
      type: boolean
      description: Is product in deposit system
    market:
      type: object
      properties:
        entryDate:
          type: string
          format: date-time
          x-stoplight:
            id: jovvcg3atuc82
        exitDate:
          type: string
          format: date-time
          x-stoplight:
            id: fjy6meqa13h6z
      x-stoplight:
        id: ap1aw4pc0eibf
